management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

spring:
  jmx:
    enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    thymeleaf:
      suffix: .html

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

    show-sql: false


logging:
  file:
    path: ./
  level:
    ROOT: INFO