spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: false

application:
  apiUrl: "/api/v1/flights"
  apiKey: "{apiKey}"
  apiHost: "booking-com15.p.rapidapi.com"
  userName: "flights_searching_monitoring_bot"
  botToken: "{botToken}"
  webHookPath: "https://a7ed-5-167-94-241.ngrok-free.app"
  locale: ru_RU

subscriptions:
  processPeriod: 180000

logging:
  level:
    ROOT: INFO
