management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: homework_18
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=PostgreSQL
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

    show-sql: true

server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}

logging:
  level:
    ROOT: ERROR